import logging
from typing import Literal

from app.config import settings
from app.pipeline.state import VideoGenerationState

logger = logging.getLogger(__name__)


def _validation_failure(state: VideoGenerationState, reason: str) -> dict:
    retry_count = state.get("retry_count", 0) + 1
    logger.warning("[validator] %s", reason)
    return {"error_reason": reason, "retry_count": retry_count}


def validate_script_node(state: VideoGenerationState) -> dict:
    """Apply the approved pedagogical checks and count a failed attempt."""
    script = state.get("script")

    if script is None:
        return _validation_failure(
            state,
            state.get("error_reason") or "No script generated by LLM",
        )

    if not script.title.strip():
        return _validation_failure(state, "Script title is empty")

    if len(script.chunks) < 3:
        return _validation_failure(
            state,
            f"Script has only {len(script.chunks)} chunks; required minimum is 3",
        )

    for index, chunk in enumerate(script.chunks):
        if not chunk.heading.strip() or not chunk.narration.strip():
            return _validation_failure(
                state,
                f"Chunk {index} has empty heading or narration",
            )

    return {"error_reason": None}


def script_router(state: VideoGenerationState) -> Literal["pass", "retry", "failed"]:
    """Route post-validation state with at most two regeneration attempts."""
    if state.get("error_reason") is None and state.get("script") is not None:
        return "pass"

    retry_count = state.get("retry_count", 0)
    if retry_count <= settings.max_retries:
        logger.info(
            "[validator] Retrying after failed attempt %s/%s",
            retry_count,
            settings.max_retries,
        )
        return "retry"

    logger.error("[validator] Max retries exceeded. Failing job.")
    return "failed"
